### ISSUE TITLE
#CSU001 - [FRONT] Criar tela de login ao sistema

### ISSUE THREAD

**Issue by samuelvictorol** [samuelvictorol/FavTab#1]
## [FRONTEND] FAVTAB Task
- Criar layout de login e registro de usuários permitiando o acesso ao sistema FAVTAB

# Geral
- [x] Criar formulário de login contendo Login e Senha
- [x] Criar formulário de registro de novo usuário com Login, Senha, Confirmação de Senha e Email
- [ ] Integração com backend

# Login
- [ ] Validar Login e Senha obrigatórios
- [ ] Guardar Login no Local/Session Storage
- [ ] Redirecionar pra tela inicial
- [ ] Caso login for inválido, mostrar mensagem de erro retornada do backend e retornar ao login

# Registrar 
- [ ] Validar Login, Email, Senha e Confirmação de Senha como obrigatórios
- [ ] Guardar usuário no banco de dados
- [ ] Redirecionar pra tela inicial
- [ ] Caso registro for inválido, mostrar mensagem de erro retornada do backend

## Tasks Relacionadas:
-  [backend csu002](https://github.com/samuelvictorol/FavTab/issues/2)
