### ISSUE TITLE
#CSU002 - [BACK] Endpoints de acesso ao sistema

### ISSUE THREAD

**Issue by samuelvictorol** [samuelvictorol/FavTab#2]
## [BACKEND] FAVTAB Task
- Criar endpoint para validação de login e registro de usuários salvando os dados no banco.

# Geral
- [ ] Criar Endpoint para validação de login
- [ ] Criar Endpoint para criação e validação de registro de usuários
- [ ] Criar Endpoint + Serviço "Esqueci minha Senha"
# Login
- [ ] Validar Login e Senha obrigatórios
- [ ] Validar Login e senha do usuário
- [ ] Retornar mensagem de sucesso no login, credenciais inválidas ou erro de conexão

# Registrar 
- [ ] Validar Login, Email, Senha e Confirmação de Senha como obrigatórios
- [ ] Validar existência de login ou email
- [ ] Salvar usuário no banco
- [ ] Retornar mensagem de sucesso no criação, credenciais já existente ou erro de conexão

# Modelagem
```json
User {
 "id": number,
 "login": string(30),
 "descricao":  string(200),
 "email":  string(200),
 "imgUrl": string(150),
},
Repertorio{
 "id": number,
 "titulo": string(30),
 "descricao":  string(200),
 "likes":  number,
 "privado": boolean,
 "createdBy": user
} ,
Musica {
 "id": number,
 "titulo": string(30),
 "descricao":  string(200),
 "links":  string[],
 "createdBy": user
}
```

## Tasks Relacionadas:
-  [frontend csu001](https://github.com/samuelvictorol/FavTab/issues/1)
