### ISSUE TITLE
#CSU005 - [FRONT] Tela Criação de Repertórios e Músicas

### ISSUE THREAD

**Issue by samuelvictorol** [samuelvictorol/FavTab#5]
## [FRONTEND] FAVTAB Task
- Permitir que ao usuário a criação de novos repertórios e criar e vincular musicas a eles

# Geral
- [ ] Criar Tela para criação de repertório contendo o nome e descrição da playlist e opção ser privada
- [ ] Criar Tela para criação de musicas contendo nome e links utils relacionados às cifras, audio etc.
- [ ] Integrar ao backend

## Tasks Relacionadas:
-  [backend csu004](https://github.com/samuelvictorol/FavTab/issues/4)
